import HeroSection from './components/UI/HeroSection'
import AboutTabs from './components/AboutTabs/AboutTabs'
import ProjectsGrid from './components/ProjectsGrid/ProjectsGrid'
import type { Metadata } from 'next'
import HeadingCenter from './components/UI/HeadingCenter'
import HeadingLeft from './components/UI/HeadingLeft'
import PastelMarquee from './components/UI/PastelMarquee'
import ContactMeDialog from './components/UI/ContactMeDialog'

export const metadata: Metadata = {
  title: "Main Page – Fedor Tatarintsev",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <div className="container-second">
        <HeroSection />

      </div>
      <PastelMarquee />
      <div className="container">
        <HeadingCenter className='text-6xl text-transparent bg-clip-text bg-gradient-to-r from-[#7e8b4a] to-[#D3E97A] max-sm:text-5xl'>About Me</HeadingCenter>
        <AboutTabs />
        <HeadingLeft className='my-8 text-6xl text-transparent bg-clip-text bg-gradient-to-r from-[#7e8b4a] to-[#D3E97A] max-sm:text-5xl'>Projects</HeadingLeft>
        <ProjectsGrid limit={6} />
      </div>
      <ContactMeDialog />
    </>
  )
}
